---
linters-settings:
  goimports:
    local-prefixes: github.com/leaktk/scanner

linters:
  # Specify the linters that we want to use
  disable-all: true
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
