version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/leaktk/scanner
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
